// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package es_test

import (
	"context"
	"github.com/kyuff/es"
	"iter"
	"sync"
)

// Ensure, that ReadWriterMock does implement es.ReadWriter.
// If this is not the case, regenerate this file with moq.
var _ es.ReadWriter = &ReadWriterMock{}

// ReadWriterMock is a mock implementation of es.ReadWriter.
//
//	func TestSomethingThatUsesReadWriter(t *testing.T) {
//
//		// make and configure a mocked es.ReadWriter
//		mockedReadWriter := &ReadWriterMock{
//			ReadFunc: func(ctx context.Context, entityType string, entityID string, eventNumber int64) iter.Seq2[es.Event, error] {
//				panic("mock out the Read method")
//			},
//			WriteFunc: func(ctx context.Context, entityType string, events iter.Seq2[es.Event, error]) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedReadWriter in code that requires es.ReadWriter
//		// and then make assertions.
//
//	}
type ReadWriterMock struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, entityType string, entityID string, eventNumber int64) iter.Seq2[es.Event, error]

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, entityType string, events iter.Seq2[es.Event, error]) error

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EntityType is the entityType argument value.
			EntityType string
			// EntityID is the entityID argument value.
			EntityID string
			// EventNumber is the eventNumber argument value.
			EventNumber int64
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EntityType is the entityType argument value.
			EntityType string
			// Events is the events argument value.
			Events iter.Seq2[es.Event, error]
		}
	}
	lockRead  sync.RWMutex
	lockWrite sync.RWMutex
}

// Read calls ReadFunc.
func (mock *ReadWriterMock) Read(ctx context.Context, entityType string, entityID string, eventNumber int64) iter.Seq2[es.Event, error] {
	if mock.ReadFunc == nil {
		panic("ReadWriterMock.ReadFunc: method is nil but ReadWriter.Read was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		EntityType  string
		EntityID    string
		EventNumber int64
	}{
		Ctx:         ctx,
		EntityType:  entityType,
		EntityID:    entityID,
		EventNumber: eventNumber,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, entityType, entityID, eventNumber)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedReadWriter.ReadCalls())
func (mock *ReadWriterMock) ReadCalls() []struct {
	Ctx         context.Context
	EntityType  string
	EntityID    string
	EventNumber int64
} {
	var calls []struct {
		Ctx         context.Context
		EntityType  string
		EntityID    string
		EventNumber int64
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *ReadWriterMock) Write(ctx context.Context, entityType string, events iter.Seq2[es.Event, error]) error {
	if mock.WriteFunc == nil {
		panic("ReadWriterMock.WriteFunc: method is nil but ReadWriter.Write was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		EntityType string
		Events     iter.Seq2[es.Event, error]
	}{
		Ctx:        ctx,
		EntityType: entityType,
		Events:     events,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, entityType, events)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedReadWriter.WriteCalls())
func (mock *ReadWriterMock) WriteCalls() []struct {
	Ctx        context.Context
	EntityType string
	Events     iter.Seq2[es.Event, error]
} {
	var calls []struct {
		Ctx        context.Context
		EntityType string
		Events     iter.Seq2[es.Event, error]
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// Ensure, that StorageMock does implement es.Storage.
// If this is not the case, regenerate this file with moq.
var _ es.Storage = &StorageMock{}

// StorageMock is a mock implementation of es.Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked es.Storage
//		mockedStorage := &StorageMock{
//			GetStreamIDsFunc: func(ctx context.Context, streamType string, storeStreamID string, limit int64) ([]string, string, error) {
//				panic("mock out the GetStreamIDs method")
//			},
//			ReadFunc: func(ctx context.Context, streamType string, streamID string, eventNumber int64) iter.Seq2[es.Event, error] {
//				panic("mock out the Read method")
//			},
//			RegisterFunc: func(streamType string, types ...es.Content) error {
//				panic("mock out the Register method")
//			},
//			StartPublishFunc: func(ctx context.Context, w es.Writer) error {
//				panic("mock out the StartPublish method")
//			},
//			WriteFunc: func(ctx context.Context, streamType string, events iter.Seq2[es.Event, error]) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedStorage in code that requires es.Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// GetStreamIDsFunc mocks the GetStreamIDs method.
	GetStreamIDsFunc func(ctx context.Context, streamType string, storeStreamID string, limit int64) ([]string, string, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, streamType string, streamID string, eventNumber int64) iter.Seq2[es.Event, error]

	// RegisterFunc mocks the Register method.
	RegisterFunc func(streamType string, types ...es.Content) error

	// StartPublishFunc mocks the StartPublish method.
	StartPublishFunc func(ctx context.Context, w es.Writer) error

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, streamType string, events iter.Seq2[es.Event, error]) error

	// calls tracks calls to the methods.
	calls struct {
		// GetStreamIDs holds details about calls to the GetStreamIDs method.
		GetStreamIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// StreamType is the streamType argument value.
			StreamType string
			// StoreStreamID is the storeStreamID argument value.
			StoreStreamID string
			// Limit is the limit argument value.
			Limit int64
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// StreamType is the streamType argument value.
			StreamType string
			// StreamID is the streamID argument value.
			StreamID string
			// EventNumber is the eventNumber argument value.
			EventNumber int64
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// StreamType is the streamType argument value.
			StreamType string
			// Types is the types argument value.
			Types []es.Content
		}
		// StartPublish holds details about calls to the StartPublish method.
		StartPublish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// W is the w argument value.
			W es.Writer
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// StreamType is the streamType argument value.
			StreamType string
			// Events is the events argument value.
			Events iter.Seq2[es.Event, error]
		}
	}
	lockGetStreamIDs sync.RWMutex
	lockRead         sync.RWMutex
	lockRegister     sync.RWMutex
	lockStartPublish sync.RWMutex
	lockWrite        sync.RWMutex
}

// GetStreamIDs calls GetStreamIDsFunc.
func (mock *StorageMock) GetStreamIDs(ctx context.Context, streamType string, storeStreamID string, limit int64) ([]string, string, error) {
	if mock.GetStreamIDsFunc == nil {
		panic("StorageMock.GetStreamIDsFunc: method is nil but Storage.GetStreamIDs was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		StreamType    string
		StoreStreamID string
		Limit         int64
	}{
		Ctx:           ctx,
		StreamType:    streamType,
		StoreStreamID: storeStreamID,
		Limit:         limit,
	}
	mock.lockGetStreamIDs.Lock()
	mock.calls.GetStreamIDs = append(mock.calls.GetStreamIDs, callInfo)
	mock.lockGetStreamIDs.Unlock()
	return mock.GetStreamIDsFunc(ctx, streamType, storeStreamID, limit)
}

// GetStreamIDsCalls gets all the calls that were made to GetStreamIDs.
// Check the length with:
//
//	len(mockedStorage.GetStreamIDsCalls())
func (mock *StorageMock) GetStreamIDsCalls() []struct {
	Ctx           context.Context
	StreamType    string
	StoreStreamID string
	Limit         int64
} {
	var calls []struct {
		Ctx           context.Context
		StreamType    string
		StoreStreamID string
		Limit         int64
	}
	mock.lockGetStreamIDs.RLock()
	calls = mock.calls.GetStreamIDs
	mock.lockGetStreamIDs.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *StorageMock) Read(ctx context.Context, streamType string, streamID string, eventNumber int64) iter.Seq2[es.Event, error] {
	if mock.ReadFunc == nil {
		panic("StorageMock.ReadFunc: method is nil but Storage.Read was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		StreamType  string
		StreamID    string
		EventNumber int64
	}{
		Ctx:         ctx,
		StreamType:  streamType,
		StreamID:    streamID,
		EventNumber: eventNumber,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, streamType, streamID, eventNumber)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedStorage.ReadCalls())
func (mock *StorageMock) ReadCalls() []struct {
	Ctx         context.Context
	StreamType  string
	StreamID    string
	EventNumber int64
} {
	var calls []struct {
		Ctx         context.Context
		StreamType  string
		StreamID    string
		EventNumber int64
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *StorageMock) Register(streamType string, types ...es.Content) error {
	if mock.RegisterFunc == nil {
		panic("StorageMock.RegisterFunc: method is nil but Storage.Register was just called")
	}
	callInfo := struct {
		StreamType string
		Types      []es.Content
	}{
		StreamType: streamType,
		Types:      types,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(streamType, types...)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedStorage.RegisterCalls())
func (mock *StorageMock) RegisterCalls() []struct {
	StreamType string
	Types      []es.Content
} {
	var calls []struct {
		StreamType string
		Types      []es.Content
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// StartPublish calls StartPublishFunc.
func (mock *StorageMock) StartPublish(ctx context.Context, w es.Writer) error {
	if mock.StartPublishFunc == nil {
		panic("StorageMock.StartPublishFunc: method is nil but Storage.StartPublish was just called")
	}
	callInfo := struct {
		Ctx context.Context
		W   es.Writer
	}{
		Ctx: ctx,
		W:   w,
	}
	mock.lockStartPublish.Lock()
	mock.calls.StartPublish = append(mock.calls.StartPublish, callInfo)
	mock.lockStartPublish.Unlock()
	return mock.StartPublishFunc(ctx, w)
}

// StartPublishCalls gets all the calls that were made to StartPublish.
// Check the length with:
//
//	len(mockedStorage.StartPublishCalls())
func (mock *StorageMock) StartPublishCalls() []struct {
	Ctx context.Context
	W   es.Writer
} {
	var calls []struct {
		Ctx context.Context
		W   es.Writer
	}
	mock.lockStartPublish.RLock()
	calls = mock.calls.StartPublish
	mock.lockStartPublish.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *StorageMock) Write(ctx context.Context, streamType string, events iter.Seq2[es.Event, error]) error {
	if mock.WriteFunc == nil {
		panic("StorageMock.WriteFunc: method is nil but Storage.Write was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		StreamType string
		Events     iter.Seq2[es.Event, error]
	}{
		Ctx:        ctx,
		StreamType: streamType,
		Events:     events,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, streamType, events)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedStorage.WriteCalls())
func (mock *StorageMock) WriteCalls() []struct {
	Ctx        context.Context
	StreamType string
	Events     iter.Seq2[es.Event, error]
} {
	var calls []struct {
		Ctx        context.Context
		StreamType string
		Events     iter.Seq2[es.Event, error]
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// Ensure, that HandlerMock does implement es.Handler.
// If this is not the case, regenerate this file with moq.
var _ es.Handler = &HandlerMock{}

// HandlerMock is a mock implementation of es.Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked es.Handler
//		mockedHandler := &HandlerMock{
//			HandleFunc: func(ctx context.Context, event es.Event) error {
//				panic("mock out the Handle method")
//			},
//		}
//
//		// use mockedHandler in code that requires es.Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(ctx context.Context, event es.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event es.Event
		}
	}
	lockHandle sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *HandlerMock) Handle(ctx context.Context, event es.Event) error {
	if mock.HandleFunc == nil {
		panic("HandlerMock.HandleFunc: method is nil but Handler.Handle was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event es.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	return mock.HandleFunc(ctx, event)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedHandler.HandleCalls())
func (mock *HandlerMock) HandleCalls() []struct {
	Ctx   context.Context
	Event es.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event es.Event
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}
