// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package inmemory_test

import (
	"context"
	"github.com/kyuff/es"
	"github.com/kyuff/es/storage/inmemory"
	"iter"
	"sync"
)

// Ensure, that WriterMock does implement inmemory.Writer.
// If this is not the case, regenerate this file with moq.
var _ inmemory.Writer = &WriterMock{}

// WriterMock is a mock implementation of inmemory.Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked inmemory.Writer
//		mockedWriter := &WriterMock{
//			WriteFunc: func(ctx context.Context, streamType string, events iter.Seq2[es.Event, error]) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedWriter in code that requires inmemory.Writer
//		// and then make assertions.
//
//	}
type WriterMock struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, streamType string, events iter.Seq2[es.Event, error]) error

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// StreamType is the streamType argument value.
			StreamType string
			// Events is the events argument value.
			Events iter.Seq2[es.Event, error]
		}
	}
	lockWrite sync.RWMutex
}

// Write calls WriteFunc.
func (mock *WriterMock) Write(ctx context.Context, streamType string, events iter.Seq2[es.Event, error]) error {
	if mock.WriteFunc == nil {
		panic("WriterMock.WriteFunc: method is nil but Writer.Write was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		StreamType string
		Events     iter.Seq2[es.Event, error]
	}{
		Ctx:        ctx,
		StreamType: streamType,
		Events:     events,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, streamType, events)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedWriter.WriteCalls())
func (mock *WriterMock) WriteCalls() []struct {
	Ctx        context.Context
	StreamType string
	Events     iter.Seq2[es.Event, error]
} {
	var calls []struct {
		Ctx        context.Context
		StreamType string
		Events     iter.Seq2[es.Event, error]
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
